import { useEffect,useState } from 'react';import { api } from '../services/api';

export default function BackupPanel(){
  const [items,setItems]=useState([]),[msg,setMsg]=useState(null),[restoreTarget,setRestoreTarget]=useState(null),[loading,setLoading]=useState(false);
  const show=(message,type='success')=>setMsg({message,type});
  async function load(){try{setItems(await api.get('/backups'))}catch(e){show('Yedekler yüklenemedi: '+e.message,'error')}}
  async function create(){setLoading(true);try{await api.post('/backups/create');show('Yedek başarıyla oluşturuldu.');load()}catch(e){show('Yedek oluşturulamadı: '+e.message,'error')}finally{setLoading(false)}}
  async function del(f){setLoading(true);try{await api.del('/backups/'+encodeURIComponent(f));show('Yedek silindi.');load()}catch(e){show('Yedek silinemedi: '+e.message,'error')}finally{setLoading(false)}}
  async function restore(){if(!restoreTarget)return;setLoading(true);try{await api.post('/backups/restore',{filename:restoreTarget.filename});setRestoreTarget(null);show('Yedek başarıyla geri yüklendi.');load()}catch(e){show('Yedek geri yüklenemedi: '+e.message,'error')}finally{setLoading(false)}}
  useEffect(()=>{load()},[]);
  return <div className="card space-y-4"><div className="flex justify-between items-start gap-4"><div><h2 className="section-title">Yedekleme</h2><p className="section-help">Veritabanı yedeği oluşturabilir, mevcut yedekleri geri yükleyebilir veya silebilirsiniz.</p></div><button className="btn" disabled={loading} onClick={create}>Yedek Oluştur</button></div>{msg&&<p className={`text-sm border p-3 rounded-xl ${msg.type==='error'?'bg-red-50 text-red-800 border-red-100':'bg-emerald-50 text-emerald-800 border-emerald-100'}`}>{msg.message}</p>}{items.length===0?<p className="friendly-empty p-4 rounded-xl">Henüz yedek yok.</p>:<ul className="divide-y">{items.map(b=><li className="flex flex-col md:flex-row md:items-center justify-between gap-3 py-3" key={b.filename}><div><p className="font-medium text-slate-800">{b.filename}</p><p className="text-xs text-slate-500">{Math.round((b.size||0)/1024)} KB</p></div><div className="flex gap-2"><button className="btn-light" disabled={loading} onClick={()=>setRestoreTarget(b)}>Geri Yükle</button><button className="btn-light text-red-700" disabled={loading} onClick={()=>del(b.filename)}>Sil</button></div></li>)}</ul>}{restoreTarget&&<div className="fixed inset-0 bg-slate-900/40 flex items-center justify-center p-4 z-50"><div className="bg-white rounded-2xl shadow-xl max-w-lg w-full p-6 space-y-4"><h3 className="text-xl font-bold text-slate-800">Yedeği Geri Yükle</h3><p className="text-slate-700">Bu yedeği geri yüklemek üzeresiniz. Mevcut veritabanı önce güvenlik yedeği alınarak değiştirilecektir. Devam etmek istiyor musunuz?</p><p className="text-sm bg-slate-50 p-3 rounded-xl break-all">{restoreTarget.filename}</p><div className="flex justify-end gap-2"><button className="btn-light" disabled={loading} onClick={()=>setRestoreTarget(null)}>Vazgeç</button><button className="btn" disabled={loading} onClick={restore}>Evet, Geri Yükle</button></div></div></div>}</div>
}
