import { useEffect,useState } from 'react';import { api } from '../services/api';

const API_BASE = import.meta.env.VITE_API_BASE || 'http://localhost:4000/api';

async function parseImportResponse(res) {
  const contentType = res.headers.get('content-type') || '';
  const data = contentType.includes('application/json') ? await res.json() : await res.text();
  if (res.ok) return data;
  const raw = typeof data === 'string' ? data : (data.error || data.message || '');
  if (raw.includes('PayloadTooLargeError') || raw.includes('request entity too large') || raw.includes('entity.too.large')) throw new Error('Dosya çok büyük. Lütfen daha küçük bir Excel/CSV dosyası deneyin veya dosyayı parçalara bölün.');
  if (raw.trim().startsWith('<!DOCTYPE') || raw.trim().startsWith('<html')) throw new Error('İçe aktarma sırasında hata oluştu. Lütfen dosyayı kontrol edin.');
  throw new Error(raw || 'İçe aktarma sırasında hata oluştu.');
}
function PreviewBox({preview,onSave,loading}){
  if(!preview)return null;
  const importable=preview.importableRows ?? preview.records.filter(r=>r.valid).length;
  const missing=preview.missingEmailRows || 0;
  const invalid=(preview.invalidRows||0)+(preview.invalidEmailRows||0);
  const rowClass=r=>r.status==='Hazır'?'':r.status==='Tekrar'?'bg-amber-50':'bg-red-50';
  return <div className="border border-sky-100 rounded-xl p-4 bg-white space-y-3"><div className="grid md:grid-cols-5 gap-3"><div className="bg-sky-50 rounded-xl p-3"><b>{preview.totalRows}</b><p className="text-xs text-slate-500">Toplam satır</p></div><div className="bg-emerald-50 rounded-xl p-3"><b>{importable}</b><p className="text-xs text-slate-500">Aktarılabilir</p></div><div className="bg-amber-50 rounded-xl p-3"><b>{preview.duplicateRows}</b><p className="text-xs text-slate-500">Tekrar</p></div><div className="bg-orange-50 rounded-xl p-3"><b>{missing}</b><p className="text-xs text-slate-500">E-posta Eksik</p></div><div className="bg-red-50 rounded-xl p-3"><b>{invalid}</b><p className="text-xs text-slate-500">Hatalı</p></div></div>{missing>0&&<p className="text-sm bg-amber-50 text-amber-800 border border-amber-100 p-3 rounded-xl">E-posta adresi olmayan kurumlar mail gönderim listesine alınamaz. Bu satırlar içe aktarılmayacak.</p>}{preview.filename&&<p className="text-sm text-slate-600">Dosya: <b>{preview.filename}</b></p>}<div className="flex justify-between items-center"><p className="font-semibold">İlk 10 örnek satır</p><button className="btn" disabled={loading||importable===0} onClick={onSave}>Kaydet / İçe Aktar</button></div><div className="max-h-64 overflow-auto"><table className="w-full text-xs"><thead><tr><th>Kurum</th><th>Şehir</th><th>E-posta</th><th>Durum / Sebep</th></tr></thead><tbody>{preview.records.slice(0,10).map((r,i)=><tr key={i} className={rowClass(r)}><td>{r.name}</td><td>{r.city}</td><td>{r.email||<span className="text-amber-700">E-posta yok</span>}</td><td>{r.status || (r.valid?'Hazır':'Hatalı')}{r.errors?.length?` — ${r.errors.join(', ')}`:''}</td></tr>)}</tbody></table></div></div>
}

export default function CsvImportPanel({onImported}){
  const [file,setFile]=useState(null),[projectFiles,setProjectFiles]=useState([]),[projectFolder,setProjectFolder]=useState(''),[selectedProjectFile,setSelectedProjectFile]=useState(''),[listType,setListType]=useState('OSGB_MARMARA'),[preview,setPreview]=useState(null),[msg,setMsg]=useState(''),[loading,setLoading]=useState(false);
  const show=e=>setMsg(typeof e==='string'?e:(e?.message||'İşlem başarısız'));
  async function loadProjectFiles(){try{const data=await api.get('/import/project-files');setProjectFolder(data.folder||'');setProjectFiles(data.files||[]);if((data.files||[]).length&&!selectedProjectFile)setSelectedProjectFile(data.files[0].filename)}catch(e){show('Proje klasörü okunamadı: '+e.message)}}
  useEffect(()=>{loadProjectFiles()},[]);
  async function doManualPreview(){if(!file)return setMsg('Lütfen dosya seçin');setLoading(true);setMsg('');try{const fd=new FormData(); fd.append('file',file); fd.append('listType',listType); const res=await fetch(API_BASE+'/import/preview',{method:'POST',body:fd}); const data=await parseImportResponse(res); setPreview(data);}catch(e){show(e)}finally{setLoading(false)}}
  async function doProjectPreview(){if(!selectedProjectFile)return setMsg('Lütfen proje klasöründen dosya seçin');setLoading(true);setMsg('');try{const data=await api.post('/import/preview-project',{filename:selectedProjectFile,listType});setPreview(data);}catch(e){show(e)}finally{setLoading(false)}}
  async function save(){if(!preview)return;setLoading(true);try{const importableRecords=preview.records.filter(r=>r.valid); const r=await api.post('/import/save',{listType,records:importableRecords});const skippedDuplicate=preview.duplicateRows||r.skippedDuplicate||0;const missingEmail=preview.missingEmailRows||r.missingEmail||0;const invalid=(preview.invalidRows||0)+(preview.invalidEmailRows||0)||r.invalid||0;setMsg(`İçe aktarıldı: ${r.imported} | Tekrar atlandı: ${skippedDuplicate} | E-posta eksik: ${missingEmail} | Hatalı: ${invalid}`);setPreview(null);setFile(null);onImported&&onImported();}catch(e){show(e)}finally{setLoading(false)}}
  return <div className="card space-y-5"><div><h2 className="section-title">Excel/CSV İçe Aktar</h2><p className="section-help mt-1">Çok sayıda kurumu dosyadan eklemek için kullanılır. Tek kurum eklemek için üstteki “Kurum Ekle” düğmesini kullanın.</p><p className="section-help mt-1">Bu klasördeki dosyalar kaynak dosyalardır. Veritabanına eklemek için dosyayı seçip Önizle ve Kaydet adımlarını tamamlayın.</p></div><label className="text-sm font-medium text-slate-700 block max-w-md">Liste tipi<select className="input mt-1" value={listType} onChange={e=>{setListType(e.target.value);setPreview(null)}}><option value="OSGB_MARMARA">Marmara OSGB Listesi</option><option value="HOSPITAL_TURKEY">Türkiye Özel Hastaneler Listesi</option></select></label><div className="border border-sky-100 rounded-xl p-4 bg-sky-50/40 space-y-3"><div><h3 className="font-bold text-slate-800">Proje Klasöründen Veri Al</h3><p className="section-help">data_collection_healthcare klasöründeki .xlsx, .xls ve .csv dosyaları burada görünür. Hiçbir dosya otomatik içe aktarılmaz.</p>{projectFiles.length===0&&projectFolder&&<p className="text-xs bg-amber-50 text-amber-800 border border-amber-100 p-2 rounded-lg mt-2">Kontrol edilen klasör: {projectFolder}</p>}</div><div className="grid md:grid-cols-4 gap-3"><label className="text-sm font-medium text-slate-700 md:col-span-3">Dosya seç<select className="input mt-1" value={selectedProjectFile} onChange={e=>{setSelectedProjectFile(e.target.value);setPreview(null)}}>{projectFiles.length===0?<option value="">Dosya bulunamadı</option>:projectFiles.map(f=><option key={f.filename} value={f.filename}>{f.filename}</option>)}</select></label><div className="flex items-end"><button className="btn w-full" disabled={loading||!selectedProjectFile} onClick={doProjectPreview}>Önizle</button></div></div></div><div className="border border-slate-100 rounded-xl p-4 bg-white space-y-3"><div><h3 className="font-bold text-slate-800">Manuel Dosya Yükle</h3><p className="section-help">Bilgisayardan ayrıca Excel/CSV seçmek için bu alanı kullanın.</p></div><div className="grid md:grid-cols-4 gap-3"><label className="text-sm font-medium text-slate-700 md:col-span-3">Dosya seç<input className="input mt-1" type="file" accept=".xlsx,.xls,.csv" onChange={e=>{setFile(e.target.files[0]);setPreview(null)}}/></label><div className="flex items-end"><button className="btn-light w-full" disabled={loading||!file} onClick={doManualPreview}>Önizle</button></div></div></div>{msg&&<p className="text-sm bg-sky-50 text-sky-800 border border-sky-100 p-3 rounded-xl">{msg}</p>}<PreviewBox preview={preview} loading={loading} onSave={save}/></div>
}
