import {useEffect,useMemo,useState} from 'react';import {api} from '../services/api';import OrganizationTable from '../components/OrganizationTable';import CsvImportPanel from '../components/CsvImportPanel';import OrganizationForm from '../components/OrganizationForm';import Toast from '../components/Toast';
import { useSearchParams } from 'react-router-dom';
import { statusLabels } from '../utils/labels';
export default function OrganizationsPage(){const [searchParams] = useSearchParams(); const mode = searchParams.get('filter'); // 'prospect' or 'client'
const [rows,setRows]=useState([]),[q,setQ]=useState(''),[type,setType]=useState(''),[status,setStatus]=useState(''),[city,setCity]=useState(''),[editing,setEditing]=useState(null),[showForm,setShowForm]=useState(false),[showImport,setShowImport]=useState(false),[toast,setToast]=useState(null);const notify=(message,type='success')=>setToast({message,type}); async function load(){setRows(await api.get('/organizations'))}useEffect(()=>{load()},[]); const cities=[...new Set(rows.map(r=>r.city).filter(Boolean))].sort(); 
const filtered=useMemo(()=>{
  let result = rows;
  if(mode === 'prospect') result = result.filter(r => r.client_status !== 'ACTIVE_CLIENT');
  if(mode === 'client') result = result.filter(r => r.client_status === 'ACTIVE_CLIENT');
  return result.filter(r=>(!q||[r.name,r.email,r.city].join(' ').toLowerCase().includes(q.toLowerCase()))&&(!type||r.type===type)&&(!status||r.status===status)&&(!city||r.city===city));
},[rows,q,type,status,city,mode]); 
async function save(f){try{ if(f.id) await api.put('/organizations/'+f.id,f); else await api.post('/organizations',f); notify('Kurum kaydedildi'); setShowForm(false); setEditing(null); load(); }catch(e){notify('Kaydedilemedi: '+e.message,'error')}} async function del(o){if(!confirm(`${o.name} silinsin mi?`))return; await api.del('/organizations/'+o.id); notify('Kurum silindi'); load()} return <div className="space-y-5"><Toast {...(toast||{})} onClose={()=>setToast(null)}/><div className="flex flex-col md:flex-row justify-between gap-4"><div><h1 className="text-2xl font-bold">{mode === 'client' ? 'Mevcut Müşteriler' : mode === 'prospect' ? 'Potansiyel Müşteriler' : 'Tüm Kurumlar'}</h1><p className="text-slate-500">Kayıtları buradan yönetebilirsiniz.</p></div><div className="flex gap-2"><button className="btn" onClick={()=>{setEditing(null);setShowForm(true);setShowImport(false)}}>Kurum Ekle</button><button className="btn-light" onClick={()=>{setShowImport(v=>!v);setShowForm(false);setEditing(null)}}>Excel/CSV İçe Aktar</button></div></div><div className="grid md:grid-cols-2 gap-4"><div className="card"><h2 className="font-bold text-slate-800">Kurum Ekle</h2><p className="section-help">Tek bir kurumu manuel eklemek/düzenlemek için kullanılır.</p></div><div className="card"><h2 className="font-bold text-slate-800">Excel/CSV İçe Aktar</h2><p className="section-help">Çok sayıda kurumu dosyadan eklemek için ayrı import panelini açar.</p></div></div>{showForm&&<OrganizationForm initial={editing} onSubmit={save} onCancel={()=>{setShowForm(false);setEditing(null)}}/>}{showImport&&<CsvImportPanel onImported={load}/>}<div className="card grid md:grid-cols-4 gap-3"><input className="input" placeholder="Ara: ad, e-posta, şehir" value={q} onChange={e=>setQ(e.target.value)}/><select className="input" value={type} onChange={e=>setType(e.target.value)}><option value="">Tüm Türler</option><option value="OSGB">OSGB</option><option value="HOSPITAL">Özel Hastane</option></select><select className="input" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tüm Durumlar</option>{['NEW','EMAIL_PLANNED','EMAIL_SENT','FOLLOW_UP_DUE','FOLLOW_UP_SENT','REPLIED','POSITIVE','NEGATIVE','CLOSED'].map(s=><option key={s} value={s}>{statusLabels[s]}</option>)}</select><select className="input" value={city} onChange={e=>setCity(e.target.value)}><option value="">Tüm Şehirler</option>{cities.map(c=><option key={c}>{c}</option>)}</select></div><OrganizationTable rows={filtered} onEdit={o=>{setEditing(o);setShowForm(true);setShowImport(false)}} onDelete={del}/></div>}
